CC = gcc
CFLAGS = -Wall -Wextra -Werror
HEADER = ./
TARGET = libft.a
AR = ar
ARFLAGS = rcv
SRC = ./ft_memset.c\
	./ft_bzero.c\
	./ft_memcpy.c\
	./ft_memccpy.c \
	./ft_memmove.c \
	./ft_memchr.c \
	./ft_memcmp.c \
	./ft_strlen.c \
	./ft_strlcpy.c \
	./ft_strlcat.c \
	./ft_strchr.c \
	./ft_strrchr.c \
	./ft_strnstr.c \
	./ft_strncmp.c \
	./ft_atoi.c \
	./ft_isalpha.c \
	./ft_isdigit.c \
	./ft_isalnum.c \
	./ft_isascii.c \
	./ft_isprint.c \
	./ft_toupper.c \
	./ft_tolower.c \
	./ft_calloc.c \
	./ft_strdup.c
OBJ = ${SRC:.c=.o}

.PHONY:all clean fclean re
all: ${TARGET}

.c.o : $(SRC)
	${CC} ${CFLAGS} -c $< -o ${<:.c=.o} -I$(HEADER)

$(TARGET): $(OBJ)
	$(AR) $(ARFLAGS) $@ $(OBJ)

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(TARGET)

re: fclean all
