CC = gcc
CFLAGS = -Wall -Wextra -Werror
HEADER = ./include
TARGET = libft.a
AR = ar
ARFLAGS = rcv
SRC = ./src/ft_memset.c\
	./src/ft_bzero.c\
	./src/ft_memcpy.c\
	./src/ft_memccpy.c \
	./src/ft_memmove.c \
	./src/ft_memchr.c \
	./src/ft_memcmp.c \
	./src/ft_strlen.c \
	./src/ft_strlcpy.c \
	./src/ft_strlcat.c \
	./src/ft_strchr.c \
	./src/ft_strrchr.c \
	./src/ft_strnstr.c \
	./src/ft_strncmp.c \
	./src/ft_atoi.c \
	./src/ft_isalpha.c \
	./src/ft_isdigit.c \
	./src/ft_isalnum.c \
	./src/ft_isascii.c \
	./src/ft_isprint.c \
	./src/ft_toupper.c \
	./src/ft_tolower.c \
	./src/ft_calloc.c \
	./src/ft_strdup.c
OBJ = ${SRC:.c=.o}

.PHONY:all clean fclean re
all: ${TARGET}

.c.o : $(SRC)
	${CC} ${CFLAGS} -c $< -o ${<:.c=.o} -I$(HEADER)

$(TARGET): $(OBJ)
	$(AR) $(ARFLAGS) $@ $(OBJ)

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(TARGET)

re: fclean all
